name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore AuthorizationServer/AuthorizationServer.csproj
    - name: Build
      run: dotnet build AuthorizationServer/AuthorizationServer.csproj --no-restore
    - name: Publish
      run: dotnet publish AuthorizationServer/AuthorizationServer.csproj -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/auth' --self-contained true  --runtime win-x86
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/auth'
